In [ ]:

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [ ]:
# # documents
# corpus = [
#     'This is the first document.',
#     'This is the second second document.',
#     'And the third one.',
#     'Is this the first document?',
# ]
def get_corpus(file_name):
    """
    :param file_name:
    :return: Return tokenized 2d string matrix
    """
    with open(file_name, 'r') as raw_text:
        corpus = raw_text.readlines()
    
    return corpus

file_name = 'train.dat'
corpus = get_corpus(file_name)
print corpus[0]

4	Catheterization laboratory events and hospital outcome with direct angioplasty for acute myocardial infarction To assess the safety of direct infarct angioplasty without antecedent thrombolytic therapy, catheterization laboratory and hospital events were assessed in consecutively treated patients with infarctions involving the left anterior descending (n = 100 patients), right (n = 100), and circumflex (n = 50) coronary arteries. The groups of patients were similar for age (left anterior descending coronary artery, 59 years; right coronary artery, 58 years; circumflex coronary artery, 62 years), patients with multivessel disease (left anterior descending coronary artery, 55%; right coronary artery, 55%; circumflex coronary artery, 64%), and patients with initial grade 0/1 antegrade flow (left anterior descending coronary artery, 79%; right coronary artery, 84%; circumflex coronary artery, 90%). Cardiogenic shock was present in eight patients with infarction of the left anterior desce

In [12]:
# count tf
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
counts = X.toarray()
print counts

[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]


In [13]:
# tf-idf term weighting
transformer = TfidfTransformer(smooth_idf=False)
tfidf = transformer.fit_transform(counts)
print tfidf.toarray()  

[[ 0.          0.43306685  0.56943086  0.43306685  0.          0.
   0.33631504  0.          0.43306685]
 [ 0.          0.24014568  0.          0.24014568  0.          0.89006176
   0.18649454  0.          0.24014568]
 [ 0.56115953  0.          0.          0.          0.56115953  0.
   0.23515939  0.56115953  0.        ]
 [ 0.          0.43306685  0.56943086  0.43306685  0.          0.
   0.33631504  0.          0.43306685]]


In [20]:
# knn
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]
n_neighbors = 3
neigh = KNeighborsClassifier(n_neighbors)
neigh.fit(X, y) 

print(neigh.predict([[1.1]]))

print(neigh.predict_proba([[0.9]]))

[0]
[[ 0.66666667  0.33333333]]
